server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  servlet:
    context-path: /bank/api/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/utdbank_db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
