export const types = {
  KREDI_TUTARI: "KREDI TUTARI",
  TAKSIT_SAYISI: "TAKSIT SAYISI",
  KAR_ORANI: "KAR ORANI",
  TAKIT_ARALIGI: "TAKSIT ARALIGI",
  VERGI_ORANI: "VERGI ORANI",
  SET_AYLİK: "SET_AYLİK",
  SET_HAFTALİK: "SET_HAFTALİK",
  SET_YİLLİK: "SET_YİLLİK",
  SET_BSMV: "SET_BSMV",
  SET_KKDF: "SET_KKDF",
};
