export const types = {
  CAPITAL: "CAPITAL",
  INSTALLMENT: "INSTALLMENT",
  PROFIT_RATE: "PROFIT RATE",
  INSTALLMENT_INTERVAL: "INSTALLMENT INTERVAL",
  TAX_RATE: "TAX_RATE",
  SET_AYLİK: "SET_AYLİK",
  SET_HAFTALİK: "SET_HAFTALİK",
  SET_YİLLİK: "SET_YİLLİK",
  SET_BSMV: "SET_BSMV",
  SET_KKDF: "SET_KKDF",
};
